
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env.STORAGE_DATABASE_URL_UNPOOLED ??
  process.env.STORAGE_POSTGRES_URL_NON_POOLING ??
  process.env.STORAGE_DATABASE_URL;

if (!databaseUrl) {
  throw new Error(
    "STORAGE_DATABASE_URL_UNPOOLED or STORAGE_DATABASE_URL is not defined",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
